// This is just a simple mockup to mimic a database. Will be removed once the real thing is in place

const newDBItems = [
  {
    itemId: '1',
    itemShortName: 'alta',
    itemType: 'product',
    itemName: 'Alta Fitness Tracker',
    itemSubheadline: '',
    itemPrice: '19900',
    itemStockQuantity: '2',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '2',
    itemShortName: 'ara',
    itemType: 'product',
    itemName: 'Project Ara Modular Smartphone',
    itemSubheadline: '',
    itemPrice: '69900',
    itemStockQuantity: '5',
    itemDescription: '',
    itemFlag: 'concept',
  },
  {
    itemId: '3',
    itemShortName: 'cane',
    itemType: 'product',
    itemName: 'Smart Walking Cane',
    itemSubheadline: '',
    itemPrice: '49900',
    itemStockQuantity: '0',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '4',
    itemShortName: 'circadia',
    itemType: 'product',
    itemName: 'Circadia Sleep Monitor',
    itemSubheadline: '',
    itemPrice: '9900',
    itemStockQuantity: '7',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '5',
    itemShortName: 'cube',
    itemName: 'The Cubes',
    itemSubheadline: '',
    itemType: 'product',
    itemPrice: '2000',
    itemStockQuantity: '12',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '6',
    itemShortName: 'electric',
    itemName: 'Zola Infinity',
    itemSubheadline: '',
    itemType: 'product',
    itemPrice: '299900',
    itemStockQuantity: '5',
    itemDescription: '',
    itemFlag: '',
  },

  {
    itemId: '7',
    itemShortName: 'orphidia',
    itemName: 'Orphidia Portable Lab Analyzer',
    itemSubheadline: '',
    itemType: 'product',
    itemPrice: '45900',
    itemStockQuantity: '4',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '8',
    itemShortName: 'pillsy',
    itemName: '',
    itemSubheadline: '',
    itemType: 'product',
    itemPrice: '9900',
    itemStockQuantity: '9',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '9',
    itemShortName: 'robot',
    itemName: 'Joseph',
    itemSubheadline: '',
    itemType: 'product',
    itemPrice: '1900000',
    itemStockQuantity: '2',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '10',
    itemShortName: 'yogurt',
    itemName: 'Yomee',
    itemSubheadline: '',
    itemType: 'product',
    itemPrice: '7900',
    itemStockQuantity: '40',
    itemDescription: '',
    itemFlag: '',
  },
  {
    itemId: '11',
    itemShortName: 'mug',
    itemName: 'Mug',
    itemSubheadline: 'A stylish mug. Who knows what it is capable of?',
    itemType: 'product',
    itemPrice: '999',
    itemStockQuantity: '999',
    itemDescription: '',
    itemFlag: '',
  },
];

export const items = [
  {
    itemId: '1',
    itemType: 'landVessel',
    itemName: 'Snow Speeder',
    itemPrice: '10000',
    itemStockQuantity: '2',
    itemDescription: '',
  },
  {
    itemId: '2',
    itemType: 'spaceShip',
    itemName: 'Tie Fighter',
    itemPrice: '20000',
    itemStockQuantity: '5',
    itemDescription: '',
  },
  {
    itemId: '3',
    itemType: 'spaceShip',
    itemName: 'X-Wing',
    itemPrice: '30000',
    itemStockQuantity: '2',
    itemDescription: '',
  },
  {
    itemId: '4',
    itemType: 'spaceShip',
    itemName: 'A-Wing',
    itemPrice: '25000',
    itemStockQuantity: '0',
    itemDescription: '',
  },
  {
    itemId: '5',
    itemName: 'Land Speeder',
    itemType: 'landVessel',
    itemPrice: '5000',
    itemStockQuantity: '6',
    itemDescription: '',
  },
  {
    itemId: '6',
    itemName: 'Cloud car',
    itemType: 'landVessel',
    itemPrice: '7500',
    itemStockQuantity: '5',
    itemDescription: '',
  },
];
