import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const featuredSectionStyles = css`
  display: flex;
  justify-content: space-evenly;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className="heroStage"
          css={css`
            /* background-image: url(/hero-background.jpg); */
            position: relative;
            width: 100vw;
            height: 66vw;
          `}
        >
          {/* <Image
            src="/hero-background.jpg"
            alt="Stylized background of Tatooine"
            layout="fill"
            objectFit="cover"
          /> */}
          <h1
            css={css`
              position: relative;
              z-index: 10;
            `}
          >
            Black Mesa
          </h1>
          <p>Delivering the future</p>
          <div
            css={css`
              box-shadow: 0px 0px 20px 20px white inset;
            `}
          >
            <Image
              src="/lambdablue-w800.jpg"
              alt="schematic placeholder"
              width="800"
              height="479"
            />
          </div>
          <div>Keyfigure 1</div>
          <div>Keyfigure 2</div>
        </div>
        <div className="featured">
          <section>
            <h2>Hot deals:</h2>
            <p>The best deals will be presented here</p>
            <div className="featuredSection" css={featuredSectionStyles}>
              <div>Card 1</div>
              <div>Card 2</div>
            </div>
          </section>
        </div>
        <div className="categories">
          <section>
            <h2>Links to the products pages</h2>
            <Link href="/spaceships">Space ships</Link>
            <Link href="/land-vessels">Land vessels</Link>
          </section>
        </div>
      </main>
    </div>
  );
}

export function getServerSideProps() {
  // workaround because of getInitialProps https://github.com/vercel/next.js/discussions/18235
  return { props: { dummie: "" } };
}
