import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const featuredSectionStyles = css`
  display: flex;
  justify-content: space-evenly;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecommerce Store</title>
        <meta
          name="description"
          content="Generated by some guy in a bootcamp"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mainWrapper">
        <main>
          <div
            className="heroStage"
            css={css`
              position: relative;
              width: 100vw;
              height: 66vw;
            `}
          >
            <h1
              css={css`
                position: relative;
                z-index: 10;
              `}
            >
              Delivering the future
            </h1>
            <p>Subheadline something something</p>

            <div>Keyfigure 1</div>
            <div>Keyfigure 2</div>
          </div>
          <div className="featured">
            <section>
              <h2>Hot deals:</h2>
              <p>The best deals will be presented here</p>
              <div className="featuredSection" css={featuredSectionStyles}>
                <div>Card 1</div>
                <div>Card 2</div>
              </div>
            </section>
          </div>
          <div className="categories">
            <section>
              <h2>Links to the products pages</h2>
              <Link href="/products">Products</Link>
              <Link href="/concepts">Concepts Studies</Link>
            </section>
          </div>
        </main>
      </div>
    </div>
  );
}

export function getServerSideProps() {
  // workaround because of getInitialProps https://github.com/vercel/next.js/discussions/18235
  return { props: { dummie: '' } };
}
