import Head from 'next/head';

export default function ThankYouPage() {
  return (
    <>
      <Head>
        <title>Thank you for your order!</title>
        <meta
          name="description"
          content="Generated by some guy in a bootcamp"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mainWrapper">
        <h1>Thank you for your order!</h1>
        <p>
          Do not worry: No order has been placed, no data was saved. This is all
          just a façade...
        </p>
      </div>
    </>
  );
}
